### ISSUE TITLE
crash after hook

### ISSUE THREAD

**Issue by Altidias** [Jiwer/mastoidhook#1]
using standard inject on extreme injector crashes shortly after hooking

**Comment by Jiwer** [comment]
I'm aware of this issue but, I'm not entirely sure why this happens. I want to believe it's an issue specific to hoi4 or extreme injector.

Use manual map injection on extreme injector or use a different injector.

**Comment by Jiwer** [comment]
![alt text](https://cdn.discordapp.com/attachments/872569792974970991/884123662930829392/affe803548c4ca133c2b85ac6f41ee4e.png)

**Comment by Altidias** [comment]
FIX:
manual mapping in extreme injector is shitty
using xenos and unlinking modules aswell as erasing PE headers on native inject works
